export const categories = [
  'Featured',
  'Newest',
  'Listening',
  'Reading',
  'Writing',
  'Speaking',
  'Overall 5+',
  'Overall 6.5+',
  'Overall 8',
  'Overall 9',
  'Overall 9x2',
  'General IELTS Preparation',
  'Academic IELTS Preparation',
  'Reading Guru',
  'Writing Expert',
  'Speaking Practice Master',
  'Experienced in Listening',
  'Most Recommended'
]
